### PR TITLE
fix: Support for new AWS region

### LINKED ISSUE #14: Error: region not found for name "eu-central-2"
## Description

Tried using the module, copied the example from [here](https://github.com/terraform-aws-modules/terraform-aws-pricing/blob/v1.2.0/examples/pricing-resources/main.tf). When running terraform plan I get this error

```
│ Error: finding Region by name
│
│   with module.eks_cluster.module.pricing.data.aws_region.one["eu-central-2"],
│   on .terraform/modules/eks_cluster.pricing/modules/pricing/regions.tf line 5, in data "aws_region" "one":
│    5: data "aws_region" "one" {
│
│ region not found for name "eu-central-2"
```

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 2.0.0

- Terraform version:

Terraform v1.1.6
- Provider version(s):

+ provider registry.terraform.io/hashicorp/aws v4.38.0
## Reproduction Code [Required]

```
module "pricing" {
  source  = "terraform-aws-modules/pricing/aws//modules/pricing"
  version = "2.0.0"

  debug_output = true

  resources = {
    "aws_instance.this" = {
      instanceType = "t3.large"
      location     = "us-east-1"
    }
  }
}
```

## Expected behavior

Looking to pricing_per_resources
## Actual behavior

Getting an error: `region not found for name "eu-central-2"`
## Additional context

I have submitted 2 PRs in the past for fixing this for other regions, is there a more permanent solution? I tried using `  skip_region_validation = true` but doesn't seem to work...

### PR DESCRIPTION
**Pull request by markandersontrocme**
## Description

Add support for new AWS region and allow users to not query all regions.

Closes https://github.com/terraform-aws-modules/terraform-aws-pricing/issues/14
## Motivation and Context

data.aws_regions queries all regions and when a new one is added this module breaks until AWS fixes the Terraform provider and aws-sdk-go
## Breaking Changes

N/A
## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by antonbabenko** [comment]
@bryantbiggs Looks like GH Actions does not like directories with dots, or? Failed run - https://github.com/terraform-aws-modules/terraform-aws-pricing/actions/runs/3463780846/jobs/5784485992

**Comment by markandersontrocme** [comment]
@antonbabenko I found the issue, it's because there's a directory called [`cost.modules.tf`](https://github.com/terraform-aws-modules/terraform-aws-pricing/tree/master/modules/cost.modules.tf) and here it is trying to open it, but it's a directory: https://github.com/clowdhaus/terraform-composite-actions/blob/main/directories/directories.py#L21

**Comment by bryantbiggs** [comment]
yes, its what @markandersontrocme has identified - the directory name looks like a file name to pythons `glob` library

**Comment by markandersontrocme** [comment]
@antonbabenko can we revert this commit (if it's the one that is causing the new GH Actions error): https://github.com/terraform-aws-modules/terraform-aws-pricing/commit/df3ccd87e807f6cd0b993f8c13bf1f99eb9f5908?

and find the fix for the module naming later? This broken module is blocking one of our pipelines...

**Comment by antonbabenko** [comment]
Let's merge this (as is) and find the fix in GH actions later.

**Comment by antonbabenko** [comment]
This PR is included in version 2.0.1 :tada:

**Comment by bryantbiggs** [comment]
this should be fixed in v1.8.3 of the action thanks to @markandersontrocme - https://github.com/clowdhaus/terraform-composite-actions/pull/16

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.0.2 :tada:

**Pull request merged**
